### ISSUE TITLE
Severe banding when using Unicorn Hat with Picamera 

### ISSUE THREAD

**Issue by Oliverhiggins93** [pimoroni/unicorn-hat-hd#43]
Hi 

I am using the Unicorn Hat HD for illumination in a microscope. Unfortunately when I capture images I find that my images have severe banding effects (rolling shutter) which corrupts the images. I am in the UK so have tried matching exposure time to both 50hz and 60hz mains frequency but the problem still persists. The only way I can alleviate this is with very long exposures (over 1 second). 

I imagine this is down to the PWM control. Is there any way to find out the PWM frequency so that I can match the exposure speed to it? Alternatively, have you ever noticed this problem before, and do you have any suggestions for solutions?

Thanks

**Comment by Gadgetoid** [comment]
I'd suggest that Unicorn HAT is woefully inadequate as a light source altogether, unless your intent is to illimunate with bias in the red/green/blue channels.

Indeed, you're probably seeing the interplay of the PWM frequency with the camera shutter, and I don't think you'll be able to easily compensate. The pixels on Unicorn HAT HD are driven by a spaghetti of custom firmware on an STM chip at around 150Hz.

**Comment by Oliverhiggins93** [comment]
Ah, that explains it. Do you know if there are any other LED matrices that Pimoroni manufactures (or from other manufacturers) that might not have this banding issue? Ideally ones at PWM frequencies that do not interfere with the camera. 

The reason I ask is that LED matrices such as this one are actually perfect for various types of structured illumination in microscopy. It is desirable to have control over the colour and direction of illumination in this case.

**Comment by Gadgetoid** [comment]
I suspect your best bet might be something that uses APA102 LEDs which have their own internal PWM generator running at ~19.2 kHz, there's some good study of these LEDs here: https://cpldcpu.wordpress.com/2014/08/27/apa102/

Our Blinkt! product uses these LEDs, but might be too small (1x8 LED array) to be any use in your application. It's relatively straight forward to run multiple Blinkt!s from a single Pi, though since they can all share the same clock pin and use different data signals.
