### ISSUE TITLE
Feature Request: Animated Weather Icons

### ISSUE THREAD

**Issue by LoveBootCaptain** [pimoroni/unicorn-hat-hd#5]
Hey there,

just wanted to ask if you would fork my animated weather icons repo for the examples.
i made some icons for old and new unicorn hat (8x8 and 16x16px).
i will maintain and update the icons as often as i can.

https://github.com/LoveBootCaptain/unicornhat_weather_icons

sadly nobody is replying to my mails to the shop how i can contribute some code. so i try this way.

would be great if i can give something back to this great project.

kind regards

Stephan

**Comment by Gadgetoid** [comment]
The best thing to do is fork this repository, add the icons and an example to display them, and submit the result as a PR. We can then let you know if anything in the example should be tweaked/changed before merging.

Fantastic work, by the way, I was looking at them just this morning and made a mental note to ask for a pull request! While I could grab the icons and whip up an example, I prefer doing it this way, since GitHub will then clearly reflect your authorship.

Normally such emails would be assigned to me, but I can't see any.

**Comment by LoveBootCaptain** [comment]
No Problem. Thx for your reply. 
The mail was concerning a refund. perhaps thats the reason you didn't get it.

I will fork the repo the next days and will add my icons and a test-example to loop them all as you suggested. Hope to get everything done this weekend.

kind regards from berlin

stephan

**Comment by LoveBootCaptain** [comment]
Pull Request is there. I'm closing this one.
